### ISSUE TITLE
Query: 

### ISSUE THREAD

**Issue by axiang99** [fireflycons/tips-for-CKA-CKAD-CKS#1]
Thank you very  much for your excellent tips!

I have a question: how can we opened mousePad in PSI?

In the screenshot I do not see the menu: https://2145393087-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-M5QaeeC1mG9VndIpgJe%2Fuploads%2FIVCOpgYXkfAyJule47C3%2FTerminal%20Emulator.png?alt=media&token=d6a2d003-d266-4a68-8c32-982f08c2e91e

Many thanks~

**Comment by fireflycons** [comment]
Not sure how you cheekily got a screenshot of a live exam environment without the proctor knowing!

As I recall, mousepad should be under the Accessories menu.

**Comment by axiang99** [comment]
Many thanks!

The screenshot is from the CNCF official guide.  

Yesterday after I clicked the picture to maximize it, I was not able to go back to main page. 

Toady finally I find it again at this link:
https://docs.linuxfoundation.org/tc-docs/certification/lf-handbook2/exam-user-interface#lf_remote_desktop69fKd8/s/-M5QaeeC1mG9VndIpgJe/certification/lf-handbook2/exam-user-interface#lf_remote_desktop
