### ISSUE TITLE
k9s can't be used in the CKA environment

### ISSUE THREAD

**Issue by Kazmirchuk** [fireflycons/tips-for-CKA-CKAD-CKS#4]
Hi and thank you so much for the excellent advices! they helped me a lot to pass my CKA exam.
Could you please add a note somewhere that k9s can't be used for the exam? I find it a super convenient tool and installed it in the killer.sh environment with snap, but when I got to the real exam, it turned out that snapcraft repos are blocked. There's absolutely no info about this in Google.  Only apt repos are allowed, and k9s is [missing](https://bugs.launchpad.net/ubuntu/+bug/2049227) from them.
I hope then people can find the answer thru Google and your repo :)

**Comment by fireflycons** [comment]
Hi @Kazmirchuk 

The answer to the above is covered by [this paragraph](https://github.com/kodekloudhub/community-faq?tab=readme-ov-file#can-i-install-packages-or-download-anything-to-the-exam-terminal) in the linked KodeKloud Community FAQ.
